#!/usr/bin/env bash
set -euo pipefail

# CI-sized lexical scale guard. Override these only when intentionally
# rebaselining docs/operations/performance.md.
export DBT_NOVA_SCALE_MODELS="${DBT_NOVA_SCALE_MODELS:-300}"
export DBT_NOVA_SCALE_PACKAGES="${DBT_NOVA_SCALE_PACKAGES:-3}"
export DBT_NOVA_SCALE_COLUMNS="${DBT_NOVA_SCALE_COLUMNS:-8}"
export DBT_NOVA_SCALE_REF_FANOUT="${DBT_NOVA_SCALE_REF_FANOUT:-2}"
export DBT_NOVA_SCALE_METRIC_EVERY="${DBT_NOVA_SCALE_METRIC_EVERY:-10}"
export DBT_NOVA_SCALE_LOAD_ITERATIONS="${DBT_NOVA_SCALE_LOAD_ITERATIONS:-2}"
export DBT_NOVA_SCALE_ITERATIONS="${DBT_NOVA_SCALE_ITERATIONS:-5}"

export DBT_NOVA_SCALE_MAX_LOAD_P95_MS="${DBT_NOVA_SCALE_MAX_LOAD_P95_MS:-30000}"
export DBT_NOVA_SCALE_MAX_SEARCH_P95_MS="${DBT_NOVA_SCALE_MAX_SEARCH_P95_MS:-2500}"
export DBT_NOVA_SCALE_MAX_INDICATOR_INVENTORY_P95_MS="${DBT_NOVA_SCALE_MAX_INDICATOR_INVENTORY_P95_MS:-2500}"
export DBT_NOVA_SCALE_MAX_COLUMN_INVENTORY_P95_MS="${DBT_NOVA_SCALE_MAX_COLUMN_INVENTORY_P95_MS:-2500}"
export DBT_NOVA_SCALE_MAX_CONTEXT_P95_MS="${DBT_NOVA_SCALE_MAX_CONTEXT_P95_MS:-2500}"
export DBT_NOVA_SCALE_MAX_HEALTH_P95_MS="${DBT_NOVA_SCALE_MAX_HEALTH_P95_MS:-1000}"

export DBT_NOVA_SEARCH_ENABLE_VECTOR=false
export DBT_NOVA_SEARCH_ENABLE_SPARSE=false
export DBT_NOVA_SEARCH_ENABLE_RERANKER=false

cargo test --locked --no-default-features --test lexical_scale_guard \
  default_lexical_manifest_paths_stay_within_scale_guard \
  -- --ignored --nocapture
